index_name: 
data_type: LOCOMO
data_root: /home/chenyizhou/LiCoMemory/dataset/locomo
dataset_name: group_1
working_dir: /home/chenyizhou/LiCoMemory/results

################################# Embedding #################################
embedding:
  api_type: "openai"
  api_key: "ollama"
  model: "nomic-embed-text:latest"
  base_url: "http://localhost:11434/v1"
  cache_dir: ""
  dimensions: 768
  max_token_size: 8102
  embed_batch_size: 8
  embedding_func_max_async: 2
  timeout: 10

#################################### LLM ####################################
llm:
  api_type: "openai"
  model: 'Qwen/Qwen3-8B-AWQ'
  base_url: "http://localhost:8910/v1"
  api_key: "EMPTY"
  
  max_token: 4096
  temperature: 0.0
  enable_concurrent: True      
  max_concurrent: 2
  timeout: 600

query_llm:
  api_type: "openai"
  base_url: "http://localhost:8910/v1"
  model: 'Qwen/Qwen3-8B-AWQ'
  api_key: "EMPTY"
  max_token: 4096
  temperature: 0.2
  timeout: 600                  

################################### Chunk ###################################
chunk:
  chunk_token_size: 1200
  chunk_overlap_token_size: 100
  token_model: qwen3:14b
  dialogue_input: True

################################# Dialogue #################################
dialog:
  enable_turn_pairing: True           
  include_session_metadata: True      
  validate_dialog_format: True        

################################# Graph #################################
graph:
  graph_type: dynamic_memory
  force: True              
  add: False   
  entity_merge_threshold: 0.85
  relationship_merge_threshold: 1

################################# Retriever #################################
retriever:
  top_k: 5  
  top_k_triples: 20
  top_chunks: 15           
  enable_summary: True            
  top_summary: 1      
  enable_visual: False       
  top_visual: 15
  enable_full: True
  enable_sessiontime: True

  enable_CogniRank: False
  summary_weight: 0.2 
  rerank_k: 0.1          

################################# Evaluation #################################
evaluation:
  enable_llm_eval: True
  eval_model: 'Qwen/Qwen3-8B-AWQ'
  eval_base_url: "http://localhost:8910/v1"
  eval_api_key: "EMPTY"
  eval_temperature: 0.0
  eval_max_tokens: 10
